# Inventory padrão: aplica no próprio host onde o ansible roda.
# Pra rodar em host remoto, basta substituir o IP e o ansible_connection.
[korp]
localhost ansible_connection=local ansible_python_interpreter=/usr/bin/python3

[korp:vars]
ansible_user={{ lookup('env', 'USER') }}
